//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChungCuDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanHo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CanHo()
        {
            this.CSVCs = new HashSet<CSVC>();
            this.CuDans = new HashSet<CuDan>();
        }
    
        public int IDCanHo { get; set; }
        public string SoPhong { get; set; }
        public Nullable<int> SoTang { get; set; }
        public string DienTich { get; set; }
        public string TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSVC> CSVCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuDan> CuDans { get; set; }
    }
}
