//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChungCuDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSVC
    {
        public int IDCSVC { get; set; }
        public string TenCSVC { get; set; }
        public string LoaiCSVC { get; set; }
        public Nullable<int> IDCanHo { get; set; }
        public Nullable<System.DateTime> NgayLapDat { get; set; }
        public Nullable<System.DateTime> NgayKiemTra { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> NVKiemTra { get; set; }
    
        public virtual CanHo CanHo { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
